{% set name = "database" %}
{% set pkg_name = "scine-" + name %}
{% set version = "1.1.0" %}

package:
  name: {{ pkg_name }}
  version: {{ version }}

source:
  - url: https://github.com/qcscine/database/archive/refs/tags/{{ version }}.tar.gz
    sha256: a9144631dfb90e06f6924cf58fc5db13719cf8577fcd3bbf788a135060a70c18
  - url: https://github.com/qcscine/development-utils/archive/refs/tags/5.0.0.tar.gz
    sha256: bb2f161ed15811def85ca635924427356564a811779993123077f4ada048be84
    folder: dev

build:
  number: 0
  skip: true  # [win]
  skip: true  # [osx]

  run_exports:
    - {{ pin_subpackage(pkg_name, max_pin='x') }}
  ignore_run_exports:
    - libblas

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - ninja
    - pkg-config
  host:
    - eigen
    - gtest
    - gmock
    # Needed for eigen detection
    - libblas
    - libmongocxx
    - mongodb
    - scine-utilsos >=5.0.0
  run:
    - mongodb

test:
  commands:
    - test -f $PREFIX/lib/lib{{ name }}${SHLIB_EXT}
    - test -d $PREFIX/include/Scine/Database/

about:
  license: BSD-3-Clause
  license_file: LICENSE.txt
  summary: |
    The SCINE database module is a database wrapper for a MongoDB encoding reaction networks
  home: https://scine.ethz.ch/
  dev_url: https://github.com/qcscine/database

extra:
  recipe-maintainers:
    - awvwgk
